package Lesson7;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;

public class New1HomeWork {

    public static final BufferedReader READER = new BufferedReader(new InputStreamReader(System.in));

    public static void main(String[] args) throws IOException {

        findRandomNumber();

    }

    public static int inputNumber() throws IOException {
        int randomNumber;
        System.out.print("type any number between 0 and 10: ");
        randomNumber = Integer.parseInt(READER.readLine());
        return randomNumber;
    }

    public static void findRandomNumber() throws IOException {
        int random = getRandom();
        boolean isCorrectNumber = true;
        while (isCorrectNumber) {
            if (inputNumber() == random) {
                System.out.println("Congratulations!!!  Random number generated by computer: " + random);

                isCorrectNumber = false;
            } else {
                System.out.println("try again loser");
            }
        }
    }

    private static int getRandom() {
        int random = (int) (Math.random() * 10);
        return random;
    }


}
